--Ejemplo DDL
CREATE TABLE EJEMPLO(
	EJEMPLO_ID NUMBER(10,0) CONSTRAINT ejemplo_pk PRIMARY KEY,
	REFERENCIA_ID NUMBER(10,0) NOT NULL REFERENCES REFERENCIA(REFERENCIA_ID),
	VALOR NUMBER(2,0) DEFAULT 1 NOT NULL CONSTRAINT valor_check CHECK(VALOR>0),
	SUMA AS(VALOR + 1) VIRTUAL
);

CREATE SEQUENCE EJEMPLO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 0
	NOMAXVALUE
	ORDER
);

CREATE TABLE REFERENCIA(
	REFERENCIA_ID NUMBER(10,0) CONSTRAINT referencia_id PRIMARY KEY
);

CREATE SEQUENCE REFERENCIA_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 0
	ORDER
;
CREATE VIEW <nombre_vista>(
	<nombre_columnas>
	AS <query>
);

CREATE VIEW VISTA(
	EJEMPLO, REFERENCIA)
	AS SELECT e.EJEMPLO_ID, r.REFERENCIA_ID FROM EJEMPLO e, REFERENCIA r WHERE e.REFERENCIA_ID = r.REFERENCIA_ID;
;

CREATE SYNONYM OTRA FOR REFERENCIA;

--Ejemplo DML
ALTER TABLE EJEMPLO
	MODIFY VALOR NUMBER(4,0)
;

ALTER TABLE EJEMPLO
	
;