--0
CREATE TABLE LIBRO(
	TITULO VARCHAR2(30) CONSTRAINT libro_pk PRIMARY KEY,
	LIBRO_ID NUMBER(10,0) NOT NULL, 
	PRECIO NUMERIC(2,1) NOT NULL,
	DESCRIPCION VARCHAR2(30) NOT NULL
);

CREATE TABLE AUTOR(
	AUTOR_ID NUMBER(10,0) NOT NULL CONSTRAINT autor_pk PRIMARY KEY,
	NOMBRE VARCHAR2(30) NOT NULL,
	TITULO VARCHAR2(30) NOT NULL CONSTRAINT autor_fk REFERENCES LIBRO(TITULO)
);

COMMIT;

--Ejercicio
ALTER TABLE AUTOR
	DROP CONSTRAINT autor_fk
;

ALTER TABLE AUTOR
	DROP COLUMN TITULO
;

ALTER TABLE LIBRO 
	DROP CONSTRAINT libro_pk	
;

ALTER TABLE LIBRO 
	ADD CONSTRAINT libro_pk PRIMARY KEY(LIBRO_ID)
;

ALTER TABLE LIBRO
	ADD AUTOR_ID NUMBER(10,0) CONSTRAINT libro_fk REFERENCES AUTOR(AUTOR_ID)
;

ALTER TABLE LIBRO
	MODIFY PRECIO NUMBER(7,5)
;

COMMIT;

INSERT INTO AUTOR(AUTOR_ID, NOMBRE) VALUES(100, 'Marcos');
INSERT INTO LIBRO(LIBRO_ID, TITULO, PRECIO, DESCRIPCION, AUTOR_ID) VALUES(1, 'Josefina', 230.10, 'Infanitil', 100 );

COMMIT;