--Ejercicio 1
--a
SELECT CLIENTE_ID, NOMBRE, NUM_TARJETA FROM CLIENTE 
MINUS
SELECT CLIENTE_ID, NOMBRE, NUM_TARJETA FROM CLIENTE 
WHERE TO_DATE('01/'||MEX_EXPIRA||'/'||ANIO_EXPIRA, 'DD/MM/YY')<SYSDATE;

--b
SELECT CLIENTE_ID, NOMBRE, AP_PATERNO, NUM_TARJETA FROM CLIENTE_ID
NATURAL JOIN PLAN NATURAL JOIN (SELECT PLAN_ID FROM PLAN_TV COUNT(NUM_RECEPTORES) AS RECEPTORES GROUP BY PLAN_ID) AS TV NATURAL JOIN PLAN_CANAL
WHERE STATUS_PLAN_ID != (SELECT STATUS_PLAN_ID FROM STATUS_PLAN WHERE DESCRIPCION = 'EXPIRADO')
AND RECEPTORES > 2 AND CANAL_ID = (SELECT CANAL_ID FROM CANAL WHERE CLASIFICACION = 'A');

--C
SELECT cliente.NOMBRE, cliente.AP_PATERNO telefono.NUM_TELEFONO estado.DESCRIPCION 
FROM CLIENTE cliente, PLAN plan, PLAN_TELEFONO telefono, ESTADO_REP estado
WHERE cliente.CLIENTE_ID=plan.CLIENTE_ID AND plan.PLAN_ID=telefono.PLAN_ID AND telefono.ESTADO_ID=estado.ESTADO_ID;

UNION

SELECT cliente.NOMBRE, cliente.AP_PATERNO, internet.MB_MES
FROM CLIENTE cliente, PLAN plan, PLAN_INTERNET internet, 
WHERE cliente.CLIENTE_ID=plan.CLIENTE_ID AND  plan.PLAN_ID=internet.PLAN_ID

UNION

SELECT cliente.NOMBRE, cliente.AP_PATERNO, television.NUM_RECEPTORES
FROM CLIENTE cliente, PLAN plan, PLAN_TV.television
WHERE cliente.CLIENTE_ID=plan.CLIENTE_ID AND  plan.PLAN_ID=television.PLAN_ID;

--d
SELECT cliente.NOMBRE, cliente.AP_PATERNO FROM CLIENTE cliente, PLAN plan,
(SELECT plan_canal.PLAN_ID, canal.CLASIFICACION, COUNT(*) FROM PLAN_CANAL plan_canal, CANAL canal WHERE plan_canal.PLAN_ID=canal.PLAN_ID AND CLASIFICACION='D' GROUP BY PLAN_ID, DESCRIPCION) AS television
WHERE cliente.CLIENTE_ID=plan.CLIENTE_ID AND plan.ṔLAN_ID=television.PLAN_ID;

--e
SELECT canal.NOMBRE, canal.NUMERO, promocion.NOMBRE AS NOMBRE_CANAL_PROMOCION, promocion.NUMERO AS NUMERO_CANAL_PROMOCION
FROM CANAL canal LEFT OUTER JOIN CANAL promocion ON canal.CANAL_ID=promocion.CANAL_ID
WHERE canal.DESCRIPCION='A';

--f
SELECT cliente.NUM_TARJETA, SUM(MONTO) AS MONTO_TOTAL FROM CLIENTE cliente, PAGO_CLIENTE pago 
WHERE cliente.CLIENTE_ID=pago.CLIENTE_ID AND MONTO>100 AND NUM_TARJETA LIKE '%0045';

--g
SELECT plan.PLAN_ID, pago.PAGO_MAS_ALTO, pago.FECHA_PAGO 
FROM CLIENTE cliente, PLAN plan, PLAN_TV television, (SELECT CLIENTE_ID, MAX(MONTO) AS PAGO_MAS_ALTO FROM PAGO_CLIENTE ORDER BY CLIENTE_ID) AS pago
WHERE cliente.CLIENTE_ID=plan.PCLIENTE_ID AND plan.PLAN_ID=television.PLAN_ID AND cliente.CLIENTE_ID=pago.CLIENTE_ID 
AND pago.FECHA_PAGO BETWEEN TO_DATE('2010/01/01', 'YYY/MM/DD') AND TO_DATE('2010/23/31', 'YYY/MM/DD');

--h
SELECT DISTINCT NOMBRE, AP_PATERNO FROM CLIENTE NATURAL JOIN PLAN 
WHERE PLAN_ID=(SELECT PLAN_ID FROM HISTORICO_STATUS_PLAN WHERE STATUS_PLAN_ID=(SELECT STATUS_PLAN_ID FROM STATUS_PLAN WHERE DESCRIPCION='SUSPENDIDO'));

--i
SELECT FECHA_STATUS AS FECHA_INICIO, COSTO_MENSUAL, AVG(COSTO_MENSUAL) AS PROMEDIO FROM PLAN 
WHERE FECHA_STATUS BETWEEN TO_DATE('2013/01/01', 'YYY/MM/DD') AND TO_DATE('2013/23/31', 'YYY/MM/DD') ;

--j
SELECT NOMBRE, AP_PATERNO, COUNT(*) AS CANALES FROM CLIENTE cliente INNER JOIN PLAN plan ON cliente.CLIENTE_ID=plan.CLIENTE_ID 
INNER JOIN PLAN_TV tv ON plan.PLAN_ID=tv.PLAN_ID
INNER JOIN PLAN_CANAL canal ON tv.PLAN_ID=canal.PLAN_ID
GROUP BY NOMBRE, AP_PATERNO
HAVING COUNT(*)>9;