--1:
SELECT NOMBRE, CLAVE_ARTICULO, STATUS_ARTICULO_ID FROM ARTICULO INNER JOIN ARTICULO_FAMOSO USING (ARTICULO_ID) WHERE NOMBRE_COMPLETO='William Harvey';
SELECT NOMBRE, CLAVE_ARTICULO, STATUS_ARTICULO_ID FROM ARTICULO NATURAL JOIN ARTICULO_FAMOSO WHERE NOMBRE_COMPLETO='William Harvey';

--2:
SELECT ARTICULO_ID, NOMBRE, CLAVE_ARTICULO FROM ARTICULO NATURAL JOIN ARTICULO_DONADO WHERE PAIS_ID=(SELECT PAIS_ID FROM PAIS WHERE DESCRIPCION='BELGICA') 
AND STATUS_ARTICULO_ID=(SELECT STATUS_ARTICULO_ID FROM STATUS_ARTICULO WHERE CLAVE='ENTREGADO');
 
--3:
SELECT ARTICULO_ID, a.NOMBRE, PRECIO_INICIAL, TIPO_ARTICULO, s.NOMBRE, FECHA_INICIO, FECHA_FIN FROM ARTICULO a INNER JOIN SUBASTA s USING(SUBASTA_ID) NATURAL JOIN SUBASTA_VENTA 
WHERE CLIENTE_ID=(SELECT CLIENTE_ID FROM CLIENTE WHERE NOMBRE='MARICELA' AND APELLIDO_PATERNO='PAEZ' AND APELLIDO_MATERNO='MARTINEZ') AND FECHA_INICIO>=TO_DATE('2010/01/01', 'YYYY/MM/DD') 
AND FECHA_INICIO<=TO_DATE('2010/12/31', 'YYYY/MM/DD');

--4:
SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, NUMERO_TARJETA, MES_VIGENCIA, ANIO_VIGENCIA  FROM CLIENTE NATURAL JOIN TARJETA_CLIENTE 
WHERE ANIO_VIGENCIA<TO_CHAR(SYSDATE, 'YY') AND MES_VIGENCIA<TO_CHAR(SYSDATE, 'MM');

--5:
SELECT NOMBRE, CLAVE_ARTICULO, TIPO_ARTICULO, ANIO_HALLAZGO, PRECIO_INICIAL, PRECIO_VENTA FROM ARTICULO a, SUBASTA_VENTA s, ARTICULO_ARQUEOLOGICO r 
WHERE a.ARTICULO_ID=s.ARTICULO_ID(+) AND a.ARTICULO_ID=r.ARTICULO_ID AND PRECIO_INICIAL>800000;

--6:
SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EMAIL, TIPO_TARJETA FROM CLIENTE c, TARJETA_CLIENTE t 
WHERE c.CLIENTE_ID=t.CLIENTE_ID(+) AND OCUPACION='ABOGADO' ORDER BY APELLIDO_PATERNO;

--7:
SELECT ARTICULO_ID, NOMBRE, CLAVE_ARTICULO, PRECIO_INICIAL, CLAVE FROM ARTICULO a, STATUS_ARTICULO s WHERE a.STATUS_ARTICULO_ID=s.STATUS_ARTICULO_ID AND PRECIO_INICIAL>900000  
INTERSECT 
SELECT ARTICULO_ID, NOMBRE, CLAVE_ARTICULO, PRECIO_INICIAL, CLAVE FROM ARTICULO a, STATUS_ARTICULO s WHERE a.STATUS_ARTICULO_ID=s.STATUS_ARTICULO_ID AND CLAVE='REGISTRADO';

--8:
SELECT c.CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,
(SELECT SUM(PRECIO_VENTA) FROM SUBASTA_VENTA s, CLIENTE c WHERE s.CLIENTE_ID=c.CLIENTE_ID) FROM CLIENTE c, SUBASTA_VENTA s
WHERE c.CLIENTE_ID=s.CLIENTE_ID ORDER BY CLIENTE_ID;

UNION
SELECT c.CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PRECIO_VENTA FROM CLIENTE c, SUBASTA_VENTA s 
WHERE c.CLIENTE_ID=s.CLIENTE_ID ORDER BY CLIENTE_ID;

SELECT SUM(PRECIO_VENTA) FROM SUBASTA_VENTA;
SELECT COUNT(SUBASTA_VENTA_ID) FROM SUBASTA_VENTA;


SELECT s.CLIENTE_ID, COUNT(SUBASTA_VENTA_ID) AS ARTICULOS  FROM CLIENTE c, SUBASTA_VENTA s WHERE c.CLIENTE_ID=s.CLIENTE_ID;

--9:
SELECT a.ARTICULO_ID, NOMBRE, CLAVE_ARTICULO, STATUS_ARTICULO_IDM ANIO_HALLAZGO FROM ARTICULO a, ARTICULO_ARQUEOLOGICO r
WHERE a.ARTICULO_ID=r.ARTICULO_ID AND ANIO_HALLAZGO<=TO_CHAR(SYSDATE, 'YYYY')-150 ORDER BY ANIO_HALLAZGO ASC;


--11:
SELECT STATUS_ARTICULO_ID, TIPO_ARTICULO, COUNT(*) FROM ARTICULO  WHERE STATUS_ARTICULO_ID=3 OR STATUS_ARTICULO_ID=4  GROUP BY STATUS_ARTICULO_ID, TIPO_ARTICULO ORDER BY STATUS_ARTICULO_ID;
