------------------------------
--DDL
------------------------------

--Creación de catalogos
CREATE TABLE TIPO_SEGURO(
	TIPO_SEGURO_ID NUMBER(10,0) CONSTRAINT tipo_seguro_pk PRIMARY KEY,
	CLAVE VARCHAR2(60) NOT NULL CONSTRAINT seguro_clave_unique UNIQUE,
	DESCRIPCION VARCHAR2(150)
);

CREATE TABLE ESTADO_REPUBLICA(
	ESTADO_REPUBLICA_ID NUMBER(10,0) CONSTRAINT estado_republica_pk PRIMARY KEY,
	CLAVE VARCHAR2(60) NOT NULL CONSTRAINT estado_clave_unique UNIQUE,
	DESCRIPCION VARCHAR2(150)	
);

CREATE TABLE MARCA_AUTO(
	MARCA_AUTO_ID NUMBER(10,0) CONSTRAINT marca_auto_pk PRIMARY KEY,
	CLAVE VARCHAR2(60) NOT NULL CONSTRAINT marca_clave_unique UNIQUE,
	DESCRIPCION VARCHAR2(150)
);

CREATE TABLE MODELO_AUTO(
	MODELO_AUTO_ID NUMBER(10,0) CONSTRAINT modelo_auto_pk PRIMARY KEY,
	CLAVE VARCHAR2(60) NOT NULL CONSTRAINT modelo_clave_unique UNIQUE,
	DESCRIPCION VARCHAR2(150)
);

CREATE TABLE ESTADO_SINIESTRO(
	ESTADO_SINIESTRO_ID NUMBER(10,0) CONSTRAINT estado_siniestro_pk PRIMARY KEY,
	CLAVE VARCHAR2(60) NOT NULL CONSTRAINT siniestro_clave_unique UNIQUE,
	DESCRIPCION VARCHAR2(150)
);

CREATE TABLE ASEGURADORA(
	ASEGURADORA_ID NUMBER(10,0) CONSTRAINT aseguradora_pk PRIMARY KEY,
	CLAVE VARCHAR2(60) NOT NULL CONSTRAINT aseguradora_clave_unique UNIQUE,
	DESCRIPCION VARCHAR2(150)
);

CREATE TABLE HOSPITAL(
	HOSPITAL_ID VARCHAR2(60) CONSTRAINT hospital_pk PRIMARY KEY,
	NOMBRE VARCHAR2(50) NOT NULL,
	DIRECCION VARCHAR2(150)
);


--Tabla complementaria para la tabla cliente
CREATE TABLE TARJETA_CLIENTE(
	TARJETA_CLIENTE_ID NUMBER(10,0) CONSTRAINT tarjeta_cliente_pk PRIMARY KEY,
	NUMERO_TARJETA VARCHAR(30) NOT NULL,
	MES_EXPIRACION VARCHAR2(2) NOT NULL CONSTRAINT mes_check CHECK (MES_EXPIRACION > 00 AND MES_EXPIRACION < 13),	
	ANIO_EXPIRACION VARCHAR2(4) NOT NULL,
	NUMERO_SEGURIDAD VARCHAR2(3) NOT NULL
);

--Tablas principales
CREATE TABLE CLIENTE(
	CLIENTE_ID NUMBER(10,0) CONSTRAINT cliente_pk PRIMARY KEY,
	NOMBRE VARCHAR2(60) NOT NULL,
	APELLIDO_PATERNO VARCHAR2(60) NOT NULL,
	APELLIDO_MATERNO VARCHAR2(60) NOT NULL,
	RFC VARCHAR2(12) NOT NULL,
	EMAIL VARCHAR2(60) NOT NULL,
	DIRECCION VARCHAR2(60) NOT NULL,
	TARJETA_CLIENTE_ID NUMBER(10,0) CONSTRAINT tarjeta_cliente_id_cliente_fk REFERENCES TARJETA_CLIENTE(TARJETA_CLIENTE_ID)
);

CREATE TABLE COTIZACION(
	COTIZACION_ID NUMBER(10,0) CONSTRAINT cotizacion_pk PRIMARY KEY,
	FECHA_COTIZACION DATE NOT NULL,
	ANIO_AUTO VARCHAR2(4) NOT NULL,
	EDAD_INICIAL_CONDUCTOR VARCHAR2(2) NOT NULL,
	EDAD_FINAL_CONDUCTOR VARCHAR2(2) NOT NULL,
	CODIGO_POSTAL VARCHAR2(20) NOT NULL,
	COSTO NUMBER(5,0),
	TIPO_SEGURO_ID 	NUMBER(10,0) NOT NULL CONSTRAINT tipos_seguro_id_cotizacion_fk REFERENCES TIPO_SEGURO(TIPO_SEGURO_ID),
	MARCA_AUTO_ID NUMBER(10,0) NOT NULL CONSTRAINT marca_auto_id_cotizacion_fk REFERENCES MARCA_AUTO(MARCA_AUTO_ID),
	MODELO_AUTO_ID NUMBER(10,0) NOT NULL CONSTRAINT modelo_auto_id_cotizacion_fk REFERENCES MODELO_AUTO(MODELO_AUTO_ID),
	ESTADO_REPUBLICA_ID NUMBER(10,0) NOT NULL CONSTRAINT estado_id_cotizacion_fk REFERENCES ESTADO_REPUBLICA(ESTADO_REPUBLICA_ID),
	CLIENTE_ID NUMBER(10,0) CONSTRAINT cliente_id_cotizacion_fk REFERENCES CLIENTE(CLIENTE_ID)
);

CREATE TABLE POLIZA(
	POLIZA_ID NUMBER(10,0) CONSTRAINT poliza_pk PRIMARY KEY,
	FOLIO VARCHAR2(13) NOT NULL CONSTRAINT folio_unique UNIQUE,
	FECHA_HORA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	NUMERO_PLACAS VARCHAR2(10) NOT NULL,
	NUMERO_SERIE VARCHAR2(60) NOT NULL,	
	SINIESTROS_OCURRIDOS NUMBER(2,0) NOT NULL,
	CLIENTE_ID NUMBER(10,0) NOT NULL CONSTRAINT cliente_id_poliza_fk REFERENCES CLIENTE(CLIENTE_ID),
	POLIZA_ANTERIOR_ID NUMBER(10,0) CONSTRAINT poliza_anterior_fk REFERENCES POLIZA(POLIZA_ID)
);


CREATE TABLE POLIZA_RESPALDO(
	POLIZA_ID NUMBER(10,0) CONSTRAINT poliza_poliza_respaldo_pk PRIMARY KEY,
	FOLIO VARCHAR2(13) NOT NULL,
	FECHA_HORA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	NUMERO_PLACAS VARCHAR2(10) NOT NULL,
	NUMERO_SERIE VARCHAR2(60) NOT NULL,	
	SINIESTROS_OCURRIDOS NUMBER(2,0) NOT NULL,
	CLIENTE_ID NUMBER(10,0) NOT NULL,
	POLIZA_ANTERIOR_ID NUMBER(10,0)
);

--Supertipo para los siniestros
CREATE TABLE SINIESTRO(
	SINIESTRO_ID NUMBER(10,0) CONSTRAINT siniestro_pk PRIMARY KEY,	
	FECHA_ESTADO DATE NOT NULL,
	ES_COLISION VARCHAR2(1) NOT NULL,
	ES_SOCIAL VARCHAR2(1) NOT NULL,
	ES_MATERIAL VARCHAR2(1) NOT NULL,
	FECHA_HORA_SINIESTRO TIMESTAMP NOT NULL,		
	DIRECCION VARCHAR2(150) NOT NULL,
	DESCRIPCION_DANIO VARCHAR2(150) NOT NULL,
	FOTO_AREA_DANIADA BLOB,
	POLIZA_ID NUMBER(10,0) NOT NULL CONSTRAINT poliza_id_siniestro_fk REFERENCES POLIZA(POLIZA_ID) ON DELETE CASCADE,
	ESTADO_SINIESTRO_ID NUMBER(10,0) NOT NULL CONSTRAINT siniestro_id_siniestro_fk REFERENCES ESTADO_SINIESTRO(ESTADO_SINIESTRO_ID)
);

--Almacenamiento de historicos
CREATE TABLE HISTORICO_ESTADO_SINIESTRO(
	HISTORICO_ESTADO_SINIESTRO_ID NUMBER(10,0) CONSTRAINT historico_estado_siniestro_pk PRIMARY KEY,
	FECHA_ESTADO DATE NOT NULL,
	SINIESTRO_ID NUMBER(10,0) NOT NULL CONSTRAINT siniestro_id_historico_fk REFERENCES SINIESTRO(SINIESTRO_ID),
	ESTADO_SINIESTRO_ID NUMBER(10,0) NOT NULL CONSTRAINT siniestro_historico_fk REFERENCES ESTADO_SINIESTRO(ESTADO_SINIESTRO_ID) 
ON DELETE CASCADE
);

--Subtipos de los siniestros
CREATE TABLE SINIESTRO_MATERIAL(
	SINIESTRO_ID NUMERIC(10,0) CONSTRAINT siniestro_material_pk PRIMARY KEY,
	NECESITA_GRUA VARCHAR2(1) NOT NULL,
	DESCRIPCION_DANIO VARCHAR2(150) NOT NULL,
	DANIO_CAUSADO BLOB,
	CONSTRAINT siniestro_material_fk FOREIGN KEY(SINIESTRO_ID) REFERENCES SINIESTRO(SINIESTRO_ID) 
ON DELETE CASCADE
);

CREATE TABLE SINIESTRO_SOCIAL(
	SINIESTRO_ID NUMERIC(10,0) CONSTRAINT siniestro_social_pk PRIMARY KEY,
	REQUIERE_AMBULANCIA VARCHAR2(1) NOT NULL,
	HOSPITAL_ID NUMERIC(10,0),
	CONSTRAINT siniestro_social_fk FOREIGN KEY(SINIESTRO_ID) REFERENCES SINIESTRO(SINIESTRO_ID) 
ON DELETE CASCADE
);

CREATE TABLE SINIESTRO_COLISION(
	SINIESTRO_ID NUMERIC(10,0) CONSTRAINT siniestro_colision_pk PRIMARY KEY,
	REPORTE_VIAL VARCHAR2(40) NOT NULL,
	REQUIERE_GRUA VARCHAR2(1) NOT NULL,
	CONSTRAINT siniestro_colision_fk FOREIGN KEY(SINIESTRO_ID) REFERENCES SINIESTRO(SINIESTRO_ID) 
ON DELETE CASCADE
);

--Tablas complementarias
CREATE TABLE PERSONA(
	PERSONA_ID NUMBER(10,0) CONSTRAINT persona_id PRIMARY KEY,
	NOMBRE VARCHAR2(60) NOT NULL,
	APELLIDO_PATERNO VARCHAR2(60) NOT NULL,
	APELLIDO_MATERNO VARCHAR2(60),
	DESCRIPCION_DANIO VARCHAR2(150),
	SINIESTRO_ID NUMBER(10,0) NOT NULL CONSTRAINT siniestro_id_persona_fk REFERENCES SINIESTRO(SINIESTRO_ID) 
ON DELETE CASCADE
);

CREATE TABLE AUTO_INVOLUCRADO(
	AUTO_INVOLUCRADO_ID NUMBER(10) CONSTRAINT auto_involucrado PRIMARY KEY,
	NUMERO_SERIE VARCHAR2(20) NOT NULL CONSTRAINT numero_serie_unique UNIQUE,
	SINIESTRO_ID NUMBER(10,0) NOT NULL CONSTRAINT siniestro_id_auto_fk REFERENCES SINIESTRO(SINIESTRO_ID) ON DELETE CASCADE,
	ASEGURADORA_ID NUMBER(10,0) NOT NULL CONSTRAINT aseguradora_id_auto_fk REFERENCES ASEGURADORA(ASEGURADORA_ID),
	MARCA_AUTO_ID NUMBER(10,0) NOT NULL CONSTRAINT marca_id_auto_fk REFERENCES MARCA_AUTO(MARCA_AUTO_ID),
	MODELO_AUTO_ID NUMBER(10,0) NOT NULL CONSTRAINT modelo_id_auto_fk REFERENCES MODELO_AUTO(MODELO_AUTO_ID)
);

--Secuencias
CREATE SEQUENCE COTIZACION_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE CLIENTE_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE TARJETA_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE POLIZA_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE SINIESTRO_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE PERSONA_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE AUTO_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

CREATE SEQUENCE HISTORICO_ESTADO_SINIESTRO_SEQ
	START WITH 0
	INCREMENT BY 1
	NOMAXVALUE
	MINVALUE 0
	ORDER
	NOCYCLE
;

--Indices
CREATE UNIQUE INDEX indice_rfc ON CLIENTE(RFC);

CREATE UNIQUE INDEX indice_email ON CLIENTE(EMAIL);

CREATE UNIQUE INDEX indice_placas ON POLIZA(NUMERO_PLACAS);

CREATE UNIQUE INDEX indice_serie ON POLIZA(NUMERO_SERIE);

CREATE UNIQUE INDEX indice_tarjeta ON TARJETA_CLIENTE(NUMERO_TARJETA);

CREATE UNIQUE INDEX indice_codigo ON COTIZACION(CODIGO_POSTAL);

--Confirmación
COMMIT;
