-----------
--Trigger 1
-----------
create or replace TRIGGER HIST_STATUS_TRIGGER
  AFTER INSERT OR UPDATE OF ESTADO_SINIESTRO_ID ON SINIESTRO
  FOR EACH ROW
  DECLARE
    V_STATUS_ID NUMBER(10,0);
    V_FECHA_STATUS DATE;
    V_HIST_ID NUMBER(10,0);
    V_SINIESTRO_ID NUMBER(10,0);
  BEGIN
    -- obtiene el consecutivo de la secuencia
    SELECT HISTORICO_ESTADO_SINIESTRO_SEQ.NEXTVAL INTO V_HIST_ID FROM DUAL;
    --asigna valores a las variables
    V_STATUS_ID := :NEW.ESTADO_SINIESTRO_ID;
    V_FECHA_STATUS := :NEW.FECHA_ESTADO;
    V_SINIESTRO_ID := :NEW.SINIESTRO_ID;
   -- DBMS_OUTPUT.PUT_LINE('STATUS ANTERIOR: '|| :OLD.ESTADO_SINIESTRO);
    --DBMS_OUTPUT.PUT_LINE('STATUS NUEVO: '|| :NEW.ESTADO_SINIESTRO);
    --DBMS_OUTPUT.PUT_LINE('INSERTANDO EN HISTORICO, LIBRO_ID: '
    --|| V_SINIESTRO_ID ||', STATUS_ID: ' || V_STATUS_ID
   --||', FECHA: '|| V_FECHA_STATUS||', HIST_ID: '||V_HIST_ID);
    -- inserta en el historico
    INSERT INTO HISTORICO_ESTADO_SINIESTRO
    (HISTORICO_ESTADO_SINIESTRO_ID,FECHA_ESTADO,SINIESTRO_ID,ESTADO_SINIESTRO_ID)
    VALUES(V_HIST_ID,V_FECHA_STATUS,V_SINIESTRO_ID,V_STATUS_ID);
  END;

-----------
--Trigger 2
-----------
create or replace TRIGGER RESPALDO_TRIGGER
  --AFTER INSERT OR UPDATE OF POLIZA_ID ON POLIZA
  BEFORE DELETE ON POLIZA
  FOR EACH ROW
  DECLARE
V_POLIZA_ID NUMBER(10,0);
V_FOLIO VARCHAR2(13);
V_FECHA_HORA_INICIO TIMESTAMP(6);
V_FECHA_FIN DATE;
V_NUMERO_PLACAS VARCHAR2(10);
V_NUMERO_SERIE VARCHAR2(40);
V_SINIESTROS_OCURRIDOS NUMBER(10,0);
V_CLIENTE_ID NUMBER(10,0);
V_POLIZA_ANTERIOR_ID NUMBER(10,0);
 BEGIN
--asigna valores a las variables
V_POLIZA_ID := :OLD.POLIZA_ID;
V_FOLIO := :OLD.FOLIO;
V_FECHA_HORA_INICIO := :OLD.FECHA_HORA_INICIO;
V_FECHA_FIN := :OLD.FECHA_FIN;
V_NUMERO_PLACAS := :OLD.NUMERO_PLACAS;
V_NUMERO_SERIE := :OLD.NUMERO_SERIE;
V_SINIESTROS_OCURRIDOS := :OLD.SINIESTROS_OCURRIDOS;
V_CLIENTE_ID := :OLD.CLIENTE_ID;
INSERT INTO poliza_respaldo(POLIZA_ID,FOLIO,FECHA_HORA_INICIO,FECHA_FIN,NUMERO_PLACAS,NUMERO_SERIE,SINIESTROS_OCURRIDOS,CLIENTE_ID) VALUES
  (V_POLIZA_ID,V_FOLIO,V_FECHA_HORA_INICIO,V_FECHA_FIN,V_NUMERO_PLACAS,V_NUMERO_SERIE,V_SINIESTROS_OCURRIDOS,V_CLIENTE_ID);
 END;

------------
--Trigger 3
-----------
create or replace TRIGGER SINIESTRO_TRIGGER
  BEFORE INSERT OR UPDATE OF SINIESTRO_ID ON SINIESTRO     
FOR EACH ROW
  DECLARE
    V_ID NUMBER(10,0);
  BEGIN
    V_ID := :NEW.POLIZA_ID;
  UPDATE POLIZA SET siniestros_ocurridos = siniestros_ocurridos+1 WHERE poliza_id = V_ID;
  END;

-----------------------------
--Confirmación de transacción
-----------------------------