--CREATES:
CREATE TABLE PLAN_ESTUDIOS(
PLAN_ESTUDIOS_ID NUMBER(2,0) CONSTRAINT plan_estudios_pk PRIMARY KEY,
CLAVE VARCHAR2(7) NOT NULL,
FECHA_APROBACION DATE NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE
);

CREATE TABLE ESTUDIANTE(
ESTUDIANTE_ID NUMBER(18,0) CONSTRAINT estudiante_pk PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
APELLIDO_MATERNO VARCHAR2(50) NOT NULL,
FOTOGRAFIA BLOB,
PLAN_ESTUDIOS_ID NOT NULL CONSTRAINT plan_estudios_id_fk REFERENCES PLAN_ESTUDIOS(PLAN_ESTUDIOS_ID)
);

CREATE TABLE ESTUDIANTE_INSCRITO(
ESTUDIANTE_ID NUMBER(18,0) NOT NULL,
ASIGNATURA_ID NUMBER(10,0) NOT NULL,
CONSTRAINT estudiante_inscrito_pk PRIMARY KEY (ESTUDIANTE_ID, ASIGNATURA_ID),
CONSTRAINT estudiante_id_estudiante_fk FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ESTUDIANTE_ID),
CONSTRAINT asignatura_id_estudiante_fk FOREIGN KEY (ASIGNATURA_ID) REFERENCES ASIGNATURA(ASIGNATURA_ID)
);

CREATE TABLE CURSO(
CURSO_ID NUMBER(18,0) CONSTRAINT curso_pk PRIMARY KEY
);

CREATE TABLE ESTUDIANTE_INSCRITO(
ESTUDIANTE_ID NUMBER(18,0) NOT NULL,
ASIGNATURA_ID NUMBER(10,0) NOT NULL,
CONSTRAINT estudiante_inscrito_pk PRIMARY KEY ESTUDIANTE_INSCRITO(ESTUDIANTE_ID, ASIGNATURA_ID),
CONSTRAINT estudiante_id_fk FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ESTUDIANTE_ID),
CONSTRAINT asignatura_id_fk FOREIGN KEY (ASIGNATURA_ID) REFERENCES ASIGNATURA(ASIGNATURA_ID)
);

CREATE TABLE HORARIO_CURSO(
HORARIO_ID NUMBER(5,0) CONSTRAINT horario_curso_pk PRIMARY KEY,
DIA_SEMANA NUMBER(1,0) NOT NULL,
HORA_INICIO DATE NOT NULL,
HORA_FIN DATE NOT NULL
);

--Aters:
ALTER TABLE PLAN_ESTUDIOS ADD CONSTRAINT clave_unique UNIQUE(CLAVE);

ALTER SEQUENCE ESTUDIANTE_SEQ
MAXVALUE 20
;

--Vistas:
CREATE VIEW V_ESTUDIANTE(
ESTUDIANTE_ID,
APELLIDO_MATERNO,
APELLIDO_PATERNO,
CLAVE_PLAN_ESTUDIOS
) AS SELECT
ESTUDIANTE_ID,
APELLIDO_PATERNO,
APELLIDO_PATERNO,
CLAVE_PLAN_ESTUDIOS
FROM
ESTUDIANTE E,
PLAN_ESTUDIOS P
WHERE
E.PLAN_ESTUDIOS_ID = P.PLAN_ESTUDIOS_ID;

--Secuencias:
CREATE SEQUENCE PLAN_ESTUDIOS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 3
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE ESTUDIANTE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 20
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE ASIGNATURA_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 3
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE HORARIO_CURSO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 3
MINVALUE 1
NOCYCLE;

--Commit
COMMIT;

--CREATES:
CREATE TABLE PROFESOR(
PROFESOR_ID NUMBER(5,0) CONSTRAINT profesor_pk PRIMARY KEY
);

--Alters:
ALTER TABLE PLAN_ESTUDIOS ADD
ACTIVO VARCHAR2(1) NOT NULL 
CONSTRAINT activo_check CHECK( ACTIVO IN ('1', '0'))
;

ALTER TABLE ESTUDIANTE_INSCRITO
DROP COLUMN ASIGNATURA_ID CASCADE CONSTRAINT;

ALTER TABLE ESTUDIANTE_INSCRITO
ADD CURSO_ID NUMBER(18,0) NOT NULL
ADD CONSTRAINT curso_id_esdtudiante_fk FOREIGN KEY (CURSO_ID) REFERENCES CURSO(CURSO_ID)
ADD CONSTRAINT estudiante_inscrito_pk PRIMARY KEY (ESTUDIANTE_ID, CURSO_ID);

ALTER TABLE CURSO
ADD PROFESOR_ID NUMBER(5,0) NOT NULL
ADD CONSTRAINT profesor_id_fk FOREIGN KEY (PROFESOR_ID) REFERENCES PROFESOR(PROFESOR_ID);

ALTER TABLE CURSO
ADD HORARIO_ID NUMBER(5,0) NOT NULL
ADD CONSTRAINT horario_id_fk FOREIGN KEY (HORARIO_ID) REFERENCES HORARIO_CURSO(HORARIO_ID);

ALTER TABLE ESTUDIANTE
DROP COLUMN FOTOGRAFIA;

ALTER TABLE ESTUDIANTE
MODIFY APELLIDO_MATERNO VARCHAR2(60) NULL;

ALTER TABLE ESTUDIANTE_INSCRITO
ADD CALIFICACION NUMBER(2,0) CONSTRAINT calificacion_menor_check CHECK(CALIFICACION>4) 
ADD CONSTRAINT calificacion_mayor_check CHECK(CALIFICACION<11);

--Commit:
COMMIT;