--A:
INSERT INTO ESTATUS_VIAJE(ESTATUS_VIAJE_ID, CLAVE, ACTIVO) VALUES (1, 'PROGRAMANDO', 1);
INSERT INTO ESTATUS_VIAJE(ESTATUS_VIAJE_ID, CLAVE, ACTIVO) VALUES (2, 'EN CURSO', 1);
INSERT INTO ESTATUS_VIAJE(ESTATUS_VIAJE_ID, CLAVE, ACTIVO) VALUES (3, 'CANCELADO', 1);
INSERT INTO ESTATUS_VIAJE(ESTATUS_VIAJE_ID, CLAVE, ACTIVO) VALUES (4, 'REALIZADO', 1);

--B:
INSERT INTO PASAJERO(PASAJERO_ID, NOMBRE, APELLIDO_PATERNO, EDAD, NUM_IDENTIFICACION) VALUES(5, 'BENITO', 'CAMPUZANO', 65, 'EJ3WACDIRJSW3485KD');

SELECT PASAJERO_ID, NOMBRE, APELLIDO_PATERNO, EDAD, NUM_IDENTIFICACION FROM PASAJERO WHERE PASAJERO_ID=5;

--C:
INSERT INTO MEDIO_TRANSPORTE(MEDIO_TRANSPORTE_ID, TIPO_MEDIO_TRANSPORTE, CAPACIDAD, CLASE) VALUES(1, 'A', 200, 'T');
INSERT INTO MEDIO_AEREO(MEDIO_TRANSPORTE_ID, AEROLINEA, NUMERO_AVION) VALUES(1,'AIR FRANCE', 'CIOP34');

--D:
INSERT INTO MEDIO_TRANSPORTE(MEDIO_TRANSPORTE_ID, TIPO_MEDIO_TRANSPORTE, CAPACIDAD, CLASE) VALUES(24, 'T', 34, 'L');
INSERT INTO MEDIO_TERRESTRE(MEDIO_TRANSPORTE_ID, MATRICULA, LINEA_TERRESTRE) VALUES(24,'12893', 'PRIMERA PLUS');

--E:
INSERT INTO LUGAR VALUES(2, 'MACHU PICHU', 'PERU');
INSERT INTO LUGAR VALUES(16, 'CRISTO REY', 'CRISTO REY BRASIL');

INSERT INTO VIAJE VALUES(1001, TO_DATE('2010/12/12 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2, 16, null, 1, SYSDATE);

INSERT INTO HISTORICO_STATUS_VIAJE VALUES(HISTORICO_STATUS_VIAJE_SEQ.NEXTVAL, SYSDATE, 1001, 1);

--F:
INSERT INTO LUGAR VALUES(15, 'BARRANCA DEL COBRE', 'BARRANCA DEL COBRE MEXICO');
INSERT INTO LUGAR VALUES(8, 'TEOTIHUACAN', 'TEOTIHUACAN MEXICO');

INSERT INTO VIAJE VALUES(1002, TO_DATE('2010/09/05 08:00:00', 'YYYY/MM/DD HH24:MI:SS'), 15, 8, 24, 1, SYSDATE);

INSERT INTO HISTORICO_STATUS_VIAJE VALUES(HISTORICO_STATUS_VIAJE_SEQ.NEXTVAL, SYSDATE, 1002, 1);

--G:
INSERT INTO LUGAR VALUES(3, 'CHICHEN ITZA', 'CHICHEN ITZA MEXICO');
INSERT INTO LUGAR VALUES(1, 'CANCUN', 'CANCUN MEX');

INSERT INTO PASAJERO VALUES(1, 'JERONIMO', 'RAMIREZ', 'JUAREZ', 34, '5578348901', '94023JU4WK45ISJDR5');

INSERT INTO MEDIO_TRANSPORTE VALUES(14, 'A', 200, 'L');
INSERT INTO MEDIO_AEREO VALUES(14, 'AEROMEXICO', 'MXA903');

INSERT INTO VIAJE VALUES(1003, TO_DATE('2011/05/01 07:50:00', 'YYYY/MM/DD HH24:MI:SS'), 3, 1, 14, 1, SYSDATE);

INSERT INTO HISTORICO_STATUS_VIAJE VALUES(HISTORICO_STATUS_VIAJE_SEQ.NEXTVAL, SYSDATE, 1003, 1);

INSERT INTO VIAJE_DETALLE VALUES(VIAJE_DETALLE_SEQ.NEXTVAL, '32F', 1003, 1);

SELECT * FROM VIAJE WHERE VIAJE_ID=1003;

--H:
UPDATE MEDIO_TRANSPORTE SET CLASE='L', CAPACIDAD=220 WHERE MEDIO_TRANSPORTE_ID = (SELECT MEDIO_TRANSPORTE_ID FROM MEDIO_AEREO WHERE NUMERO_AVION='CIOP34');

--I:
INSERT INTO MEDIO_TRANSPORTE VALUES(3, 'A', 250, 'T');
INSERT INTO MEDIO_AEREO VALUES(3, 'MEXICANA DE AVIACION', 'MX0056');

UPDATE VIAJE SET MEDIO_TRANSPORTE_ID = 3 WHERE VIAJE_ID = 1001;

--J:
INSERT INTO PASAJERO VALUES(8, 'ANTONIO', 'SERRANO', 'LUNA', 12, NULL, '98298LKJL23442342J');
INSERT INTO PASAJERO VALUES(3, 'MARIANA', 'JIMENEZ', 'LOPEZ', 23, '312383490', 'J4U58IWSLFNEIRX8R4');
INSERT INTO PASAJERO VALUES(6, 'SUSANA', 'PEREZ', 'PAEZ', 21, NULL, '834DCFR345WSFEFDSR');

INSERT INTO VIAJE_DETALLE VALUES(VIAJE_DETALLE_SEQ.NEXTVAL, '22A', 1001, 8);
INSERT INTO VIAJE_DETALLE VALUES(VIAJE_DETALLE_SEQ.NEXTVAL, '42F', 1001, 3);
INSERT INTO VIAJE_DETALLE VALUES(VIAJE_DETALLE_SEQ.NEXTVAL, '11C', 1001, 6);

SELECT * FROM VIAJE_DETALLE;

--K:

--Se obtiene el ID del medio de transporte del medio aereo del avion MXA903
SELECT MEDIO_TRANSPORTE_ID FROM MEDIO_AEREO WHERE NUMERO_AVION='MXA903';

--Una vez obtenido dicho ID, se obtiene el ID de los viajes asociados a dicho medio de transporte y en estatus programado
SELECT VIAJE_ID FROM VIAJE WHERE ESTATUS_VIAJE_ID=1 AND MEDIO_TRANSPORTE_ID=14;

--Una vez obtenido el ID del vuelo se obtiene el ID de los registros de la tabla de detalles
SELECT VIAJE_DETALLE_ID FROM VIAJE_DETALLE WHERE VIAJE_ID=1003;

--Una vez obtenido el ID del detalle se obtiene el ID de los pasajeros asociados
SELECT PASAJERO_ID FROM VIAJE_DETALLE WHERE VIAJE_DETALLE_ID=1;

--Se procede a hacer el borrado de todas las registros asociados al avión MXA903 en todas las tablas
DELETE FROM MEDIO_TRANSPORTE WHERE MEDIO_TRANSPORTE_ID=14;
DELETE FROM VIAJE_DETALLE WHERE VIAJE_ID=1003;
DELETE FROM PASAJERO WHERE PASAJERO_ID=1;
DELETE FROM HISTORICO_STATUS_VIAJE WHERE VIAJE_ID=1003;
DELETE FROM VIAJE WHERE VIAJE_ID=1003;
DELETE FROM MEDIO_AEREO WHERE NUMERO_AVION='MXA903';

--L:
CREATE TABLE PASAJERO_TEMP(
	PASAJERO_ID NUMBER(10,0) CONSTRAINT pasajero_temp_pk PRIMARY KEY,
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
	APELLIDO_MATERNO VARCHAR2(50),
	EDAD NUMBER(3,0),
	TELEFONO VARCHAR2(18), 
	NUM_IDENTIFICACION VARCHAR2(18) NOT NULL
);

INSERT INTO PASAJERO_TEMP (SELECT * FROM PASAJERO);

SELECT * FROM PASAJERO_TEMP;

