--1:
SELECT NOMBRE, CLAVE_ARTICULO, STATUS_ARTICULO_ID FROM ARTICULO INNER JOIN ARTICULO_FAMOSO USING (ARTICULO_ID) WHERE NOMBRE_COMPLETO='William Harvey';
SELECT NOMBRE, CLAVE_ARTICULO, STATUS_ARTICULO_ID FROM ARTICULO NATURAL JOIN ARTICULO_FAMOSO WHERE NOMBRE_COMPLETO='William Harvey';

--2:
SELECT ARTICULO_ID, NOMBRE, CLAVE_ARTICULO FROM ARTICULO NATURAL JOIN ARTICULO_DONADO WHERE PAIS_ID=(SELECT PAIS_ID FROM PAIS WHERE DESCRIPCION='BELGICA') 
AND STATUS_ARTICULO_ID=(SELECT STATUS_ARTICULO_ID FROM STATUS_ARTICULO WHERE CLAVE='ENTREGADO');
 
--3:
SELECT ARTICULO_ID, a.NOMBRE, PRECIO_INICIAL, TIPO_ARTICULO, s.NOMBRE, FECHA_INICIO, FECHA_FIN FROM ARTICULO a INNER JOIN SUBASTA s USING(SUBASTA_ID) NATURAL JOIN SUBASTA_VENTA 
WHERE CLIENTE_ID=(SELECT CLIENTE_ID FROM CLIENTE WHERE NOMBRE='MARICELA' AND APELLIDO_PATERNO='PAEZ' AND APELLIDO_MATERNO='MARTINEZ') AND FECHA_INICIO>=TO_DATE('2010/01/01', 'YYYY/MM/DD') 
AND FECHA_INICIO<=TO_DATE('2010/12/31', 'YYYY/MM/DD');

--4:
SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, NUMERO_TARJETA, MES_VIGENCIA, ANIO_VIGENCIA  FROM CLIENTE NATURAL JOIN TARJETA_CLIENTE 
WHERE ANIO_VIGENCIA<TO_CHAR(SYSDATE, 'YY') AND MES_VIGENCIA<TO_CHAR(SYSDATE, 'MM');

--5:
SELECT NOMBRE, CLAVE_ARTICULO, TIPO_ARTICULO, ANIO_HALLAZGO, PRECIO_INICIAL, PRECIO_VENTA FROM ARTICULO a, SUBASTA_VENTA s, ARTICULO_ARQUEOLOGICO r 
WHERE a.ARTICULO_ID=s.ARTICULO_ID(+) AND a.ARTICULO_ID=r.ARTICULO_ID AND PRECIO_INICIAL>800000;

--6:
SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EMAIL, TIPO_TARJETA FROM CLIENTE c, TARJETA_CLIENTE t 
WHERE c.CLIENTE_ID=t.CLIENTE_ID(+) AND OCUPACION='ABOGADO' ORDER BY APELLIDO_PATERNO;

--7:
SELECT ARTICULO_ID, NOMBRE, CLAVE_ARTICULO, PRECIO_INICIAL, CLAVE FROM ARTICULO a, STATUS_ARTICULO s WHERE a.STATUS_ARTICULO_ID=s.STATUS_ARTICULO_ID AND PRECIO_INICIAL>900000  
INTERSECT 
SELECT ARTICULO_ID, NOMBRE, CLAVE_ARTICULO, PRECIO_INICIAL, CLAVE FROM ARTICULO a, STATUS_ARTICULO s WHERE a.STATUS_ARTICULO_ID=s.STATUS_ARTICULO_ID AND CLAVE='REGISTRADO';

--8:
SELECT c.CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, COUNT(SUBASTA_VENTA_ID) AS ARTICULOS_COMPRADOS,SUM(PRECIO_VENTA) 
FROM CLIENTE c, SUBASTA_VENTA s WHERE c.CLIENTE_ID=s.CLIENTE_ID 
GROUP BY c.CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO
ORDER BY c.CLIENTE_ID;

--9:
SELECT a.ARTICULO_ID, NOMBRE, CLAVE_ARTICULO, STATUS_ARTICULO_IDM ANIO_HALLAZGO FROM ARTICULO a, ARTICULO_ARQUEOLOGICO r
WHERE a.ARTICULO_ID=r.ARTICULO_ID AND ANIO_HALLAZGO<=TO_CHAR(SYSDATE, 'YYYY')-150 ORDER BY ANIO_HALLAZGO ASC;

--10:
SELECT NOMBRE, TIPO_ARTICULO FROM ARTICULO 
WHERE NOMBRE LIKE 'Colonial%' AND STATUS_ARTICULO_ID != 3 AND STATUS_ARTICULO_ID != 4
ORDER BY TIPO_ARTICULO;

--11:
SELECT STATUS_ARTICULO_ID, TIPO_ARTICULO, COUNT(*) FROM ARTICULO  WHERE STATUS_ARTICULO_ID=3 OR STATUS_ARTICULO_ID=4  GROUP BY STATUS_ARTICULO_ID, TIPO_ARTICULO ORDER BY STATUS_ARTICULO_ID;

--12:
SELECT s.NOMBRE, FECHA_INICIO, LUGAR, TIPO_ARTICULO, SUM(PRECIO_VENTA) AS MONTO_TOTAL  FROM SUBASTA s, ARTICULO a, SUBASTA_VENTA v
WHERE s.SUBASTA_ID=a.SUBASTA_ID AND a.ARTICULO_ID=v.ARTICULO_ID  AND FECHA_INICIO>=TO_DATE('2009/01/01', 'YYYY/MM/DD') AND FECHA_FIN<=TO_DATE('2009/12/31', 'YYYY/MM/DD')
GROUP BY s.NOMBRE, FECHA_INICIO, LUGAR, TIPO_ARTICULO ORDER BY MONTO_TOTAL DESC;

--13:
SELECT s.SUBASTA_ID, s.NOMBRE, FECHA_INICIO, a.NOMBRE, MAX(PRECIO_VENTA) AS MONTO FROM SUBASTA s, ARTICULO a, SUBASTA_VENTA p 
WHERE s.SUBASTA_ID=a.ARTICULO_ID AND a.ARTICULO_ID=p.ARTICULO_ID AND FECHA_INICIO>=TO_DATE('2010/01/01', 'YYYY/MM/DD') AND FECHA_FIN<=TO_DATE('2010/06/30', 'YYYY/MM/DD')
GROUP BY s.SUBASTA_ID, s.NOMBRE, FECHA_INICIO, a.NOMBRE ORDER BY s.SUBASTA_ID;

--14:
SELECT SUM(PRECIO_VENTA) AS MONTO FROM SUBASTA_VENTA NATURAL JOIN CLIENTE NATURAL JOIN TARJETA_CLIENTE NATURAL JOIN
(SELECT MAX(FECHA_FACTURA) FROM FACTURA_CLIENTE) WHERE NOMBRE='GALILEA' AND APELLIDO_PATERNO='GOMEZ';

--15:
SELECT s.SUBASTA_ID, s.NOMBRE, COUNT(SUBASTA_VENTA_ID) AS ARTICULOS_VENDIDOS FROM SUBASTA s, ARTICULO c, SUBASTA_VENTA v
WHERE s.SUBASTA_ID=c.SUBASTA_ID AND c.ARTICULO_ID=v.ARTICULO_ID AND FECHA_INICIO>=TO_DATE('2010/01/01', 'YYYY/MM/DD') AND FECHA_FIN<=TO_DATE('2010/12/31', 'YYYY/MM/DD')
GROUP BY s.SUBASTA_ID, s.NOMBRE, FECHA_INICIO HAVING COUNT(SUBASTA_VENTA_ID)>3 ORDER BY SUBASTA_ID;

--16:
SELECT s.SUBASTA_ID, FECHA_INICIO, a.ARTICULO_ID, a.NOMBRE, PRECIO_INICIAL, (SELECT AVG(PRECIO_INICIAL) FROM SUBASTA_VENTA V, ARTICULO a,  SUBASTA s WHERE V.ARTICULO_ID=a.ARTICULO_ID 
AND a.SUBASTA_ID=s.SUBASTA_ID  AND FECHA_INICIO>=TO_DATE('01/07/2010', 'DD/MM/YYYY') AND FECHA_FIN<=TO_DATE('31/07/2010','DD/MM/YYYY')) AS PRECIO_PROMEDIO
FROM SUBASTA s, ARTICULO a, SUBASTA_VENTA v, CLIENTE c WHERE s.SUBASTA_ID=a.SUBASTA_ID AND v.CLIENTE_ID=c.CLIENTE_ID AND
FECHA_INICIO>=TO_DATE('01/07/2010', 'DD/MM/YYYY') AND FECHA_FIN<=TO_DATE('31/07/2010','DD/MM/YYYY') AND a.NOMBRE LIKE 'Moto%' AND STATUS_ARTICULO_ID!=1 AND STATUS_ARTICULO_ID!=2
GROUP BY s.SUBASTA_ID, FECHA_INICIO, a.ARTICULO_ID, a.NOMBRE, PRECIO_INICIAL ORDER BY SUBASTA_ID, ARTICULO_ID;

--17.-
SELECT p.PAIS_ID, p.CLAVE, p.DESCRIPCION, COUNT(p.PAIS_ID) AS ARTICULOS  FROM PAIS p, ARTICULO_DONADO d, ARTICULO a
WHERE p.PAIS_ID=d.PAIS_ID AND d.ARTICULO_ID=a.ARTICULO_ID AND PRECIO_INICIAL>300000 GROUP BY p.PAIS_ID, p.CLAVE, p.DESCRIPCION
ORDER BY ARTICULOS DESC;

--18:
SELECT S.SUBASTA_ID, s.NOMBRE, SUM(PRECIO_VENTA) FROM SUBASTA s, ARTICULO a, SUBASTA_VENTA v 
WHERE FECHA_INICIO>=TO_DATE('2010/01/01', 'YYYY/MM/DD') AND FECHA_FIN<=TO_DATE('2010/12/31', 'YYYY/MM/DD')
GROUP BY s.SUBASTA_ID, s.NOMBRE ORDER BY s.SUBASTA_ID;